//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gfycat_Random.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gfycat_Random.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die abandoned
        ///able
        ///absolute
        ///academic
        ///acceptable
        ///acclaimed
        ///accomplished
        ///accurate
        ///aching
        ///acidic
        ///acrobatic
        ///adorable
        ///adventurous
        ///babyish
        ///back
        ///bad
        ///baggy
        ///bare
        ///barren
        ///basic
        ///beautiful
        ///belated
        ///beloved
        ///calculating
        ///calm
        ///candid
        ///canine
        ///capital
        ///carefree
        ///careful
        ///careless
        ///caring
        ///cautious
        ///cavernous
        ///celebrated
        ///charming
        ///damaged
        ///damp
        ///dangerous
        ///dapper
        ///daring
        ///dark
        ///darling
        ///dazzling
        ///dead
        ///deadly
        ///deafening
        ///dear
        ///dearest
        ///each
        ///eager
        ///early
        ///earnest
        ///easy
        ///easygoing
        ///ecstatic
        ///edible
        ///educated
        ///fabulous
        ///failing
        ///faint
        ///fair
        ///faithful
        ///fake
        ///familiar
        ///fam [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string adjectives {
            get {
                return ResourceManager.GetString("adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die aardvark
        ///aardwolf
        ///abalone
        ///abyssiniancat
        ///abyssiniangroundhornbill
        ///acaciarat
        ///achillestang
        ///acornbarnacle
        ///acornweevil
        ///acornwoodpecker
        ///acouchi
        ///adamsstaghornedbeetle
        ///addax
        ///adder
        ///adeliepenguin
        ///admiralbutterfly
        ///adouri
        ///aegeancat
        ///affenpinscher
        ///afghanhound
        ///africanaugurbuzzard
        ///africanbushviper
        ///africancivet
        ///africanclawedfrog
        ///africanelephant
        ///africanfisheagle
        ///africangoldencat
        ///africangroundhornbill
        ///africanharrierhawk
        ///africanhornbill
        ///africanjacana
        ///africanmolesnake
        ///africanparadiseflycatcher
        ///africanpiedkingfisher
        ///africanporcu [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string animals {
            get {
                return ResourceManager.GetString("animals", resourceCulture);
            }
        }
    }
}
